version: '3'

services:
  api:
    image: wyveo/nginx-php-fpm:php81
    working_dir: /usr/share/nginx/slotegrator
    volumes:
      - './docker/api/slotegrator.conf:/etc/nginx/conf.d/slotegrator.conf'
      - './api:/usr/share/nginx/slotegrator'
    env_file:
      - api.env
    ports:
      - 8080:80

  db:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=slotagator
      - MYSQL_USER=slotagator
      - MYSQL_PASSWORD=slotagator
      - MYSQL_ROOT_PASSWORD=rootpass
    ports:
      - 3306:3306
    volumes:
      - './db:/var/lib/mysql'
